version: '3'
services:

  web:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php

  php:
    build: .docker
    volumes:
      - ./:/code
